### PR TITLE
fix: fix reading of LGL and NCOL files (broken in 2.0.0)

### LINKED ISSUE #1346: Failed to load graph using read.graph.ncol
### What happens, and what did you expect instead?

Trackback:

```
Error in read.graph.ncol(file, ...): INTEGER() can only be applied to a 'integer', not a 'double'
Traceback:

1. read_graph(paste(file_path, edge_files[i], sep = ""), format = "ncol", 
 .     directed = TRUE)
2. read.graph.ncol(file, ...)
```

### To reproduce

```r
shell_call <- function(command, ...) {
  result <- system(command, intern = TRUE, ...)
  cat(paste0(result, collapse = "\n"))
}

shell_call("if [[ ! -e gplus.tar.gz ]]; then wget https://snap.stanford.edu/data/gplus.tar.gz; fi")
shell_call("if [[ ! -e gplus.tar.gz ]]; then tar zxf gplus.tar.gz; fi")

remove.packages("igraph")
# install.packages("igraph", version = "1.5.1")
install.packages("devtools")
require(devtools)
install_packages("igraph", version = "1.5.1", repos=c(
    igraph = 'https://igraph.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'
  ))

library ("igraph")

graph = read_graph("gplus/100535338638690515335.edges", format="ncol", directed=TRUE)
```

### System information

It's on a google colab runtime.

Output of sessionInfo():
```
R version 4.3.3 (2024-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_2.0.3

loaded via a namespace (and not attached):
 [1] digest_0.6.29   IRdisplay_1.1   utf8_1.2.2      base64enc_0.1-3
 [5] fastmap_1.1.0   magrittr_2.0.2  glue_1.6.1      pkgconfig_2.0.3
 [9] htmltools_0.5.2 repr_1.1.7      lifecycle_1.0.1 cli_3.2.0      
[13] fansi_1.0.2     vctrs_0.3.8     pbdZMQ_0.3-11   compiler_4.3.3 
[17] tools_4.3.3     evaluate_0.15   pillar_1.7.0    ellipsis_0.3.2 
[21] rlang_1.0.1     jsonlite_1.7.3  crayon_1.5.0    IRkernel_1.3.2 
[25] uuid_1.0-3   
```

### PR DESCRIPTION
**Pull request by szhorvat**
Fixes #1346

I'm sorry, I really don't have time for a test, but I hope someone can add one based on my first comment in #1346.

### CODE REVIEW

**Comment by knwng** [comment]
Tried to add unittest for the change in https://github.com/igraph/rigraph/pull/1348. I'm new to R, so please let me know if there's anything not following common practices.

**Comment by szhorvat** [comment]
@krlmlr @Antonov548 One of the CI issues seems to be that GLPK is not found in the macOS image, so it uses the vendored GLPK.

File: tests/testthat/test-read_graph.R [hunk 1]
```diff
@@ -6,3 +6,17 @@ test_that("reading GraphML file works", {
 
   expect_true(isomorphic(g2, g))
 })
+
+test_that("reading graph in NCOL format", {
+  ncol_path <- tempfile("testfile", fileext = ".ncol")
+  g <- make_graph(c(1, 2, 2, 3))
+  write_graph(g, ncol_path, "ncol")
+  expect_no_error(g2 <- read_graph(ncol_path, "ncol"))
```
Comment (maelle) [inline tests/testthat/test-read_graph.R:14]: do we want to know more than no error?

Comment (knwng) [reply tests/testthat/test-read_graph.R:14]: > do we want to know more than no error?

I supposed g and g2 are identical at the beginning, but they are not. The graphs have the same structures but there's some difference in properties. So I replaced `expect_true(identical_graphs(g, g2))` with `expect_no_error` to meet the minimum requirement. If that's not expected, there should be other changes after thorough inspection.

File: R/foreign.R [hunk 2]
```diff
@@ -296,7 +296,7 @@ read.graph.ncol <- function(file, predef = character(0), names = TRUE,
   on.exit(.Call(R_igraph_finalizer))
   .Call(
     R_igraph_read_graph_ncol, file, as.character(predef),
-    as.logical(names), as.numeric(weights), as.logical(directed)
+    as.logical(names), weights, as.logical(directed)
```
Comment (krlmlr) [inline R/foreign.R:299]: Should this be

```suggestion
    as.logical(names), as.integer(weights), as.logical(directed)
```

?

**Review by krlmlr — COMMENTED** [review]
Why does CI/CD fail?

File: R/foreign.R (hunk 2 above)
Comment (szhorvat) [reply R/foreign.R:299]: Technically, it doesn't _need_ to be because the constants were explicitly specified as integers (`0L`, `1L`, etc.)  This is what all the auto-generated code looks like as well at the moment.

However, if you want the extra safety of `as.integer`, it doesn't hurt. It's your decision, I don't know what's good R practice. :-)

I'd just like this merged and released.

**Comment by szhorvat** [comment]
Let me know if there's anything else that you need from me here (it seems to me this is good to go).

**Comment by krlmlr** [comment]
Thanks!
