### PR TITLE
docs: fix `graph_from_adjacency_matrix()` examples to avoid warnings

### LINKED ISSUE #1290: warning in graph_from_adjacency_matrix() example
``` r
library("igraph")
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
nzs <- function(x) sort(x[x != 0])
adjm <- matrix(runif(100), 10)
adjm[adjm < 0.5] <- 0
g3 <- graph_from_adjacency_matrix((adjm + t(adjm)) / 2,
  weighted = TRUE,
  mode = "undirected"
)

g4 <- graph_from_adjacency_matrix(adjm, weighted = TRUE, mode = "max")
all(nzs(pmax(adjm, t(adjm))[upper.tri(adjm)]) == sort(E(g4)$weight))
#> Warning in nzs(pmax(adjm, t(adjm))[upper.tri(adjm)]) == sort(E(g4)$weight):
#> longer object length is not a multiple of shorter object length
#> [1] FALSE
```

<sup>Created on 2024-03-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by maelle**
Fix #1290

@clpippel does this look good? Thanks a lot for your help!

### CODE REVIEW

File: R/adjacency.R [hunk 1]
```diff
@@ -344,53 +344,103 @@ graph.adjacency.sparse <- function(adjmatrix, mode, weighted = NULL, diag = TRUE
...
 #' @examples
 #'
-#' adjm <- matrix(sample(0:1, 100, replace = TRUE, prob = c(0.9, 0.1)), ncol = 10)
-#' g1 <- graph_from_adjacency_matrix(adjm)
-#' adjm <- matrix(sample(0:5, 100,
-#'   replace = TRUE,
-#'   prob = c(0.9, 0.02, 0.02, 0.02, 0.02, 0.02)
-#' ), ncol = 10)
-#' g2 <- graph_from_adjacency_matrix(adjm, weighted = TRUE)
+#' g1 <- sample(
```
Comment (maelle) [inline R/adjacency.R:347]: this to avoid naming the adjacency matrix!

**Review by krlmlr — APPROVED** [review]
Thanks!
