### PR TITLE
fix: changed base location for graph_from_graphdb and added tests

### LINKED ISSUE #1712: How useful is `graph_from_graphdb()`?
Just noticed this function in `R/foreign.R`, that does not have any test. In the CRAN mirror I only see it in igraph repo https://github.com/search?q=graph_from_graphdb+user%3Acran&type=code&ref=advsearch

Is it useful or should it be deprecated?

### PR DESCRIPTION
**Pull request by schochastics**
Fix #1712
Downloaded the database from here: https://zenodo.org/records/11204020
and hosted it here: https://github.com/schochastics/graphsdb/

General question: should we host it somewhere else?

### CODE REVIEW

File: R/foreign.R [hunk 1]
```diff
@@ -596,12 +596,13 @@ write.graph.dot <- function(graph, file, ...) {
 #' @family foreign
 #' @export
 #' @keywords graphs
-graph_from_graphdb <- function(url = NULL,
-                               prefix = "iso", type = "r001", nodes = NULL, pair = "A", which = 0,
-                               base = "http://cneurocvs.rmki.kfki.hu/graphdb/gzip",
-                               compressed = TRUE, directed = TRUE) {
+graph_from_graphdb <- function(
```
Comment (maelle) [inline R/foreign.R:599]: is this reformatting due to Air? :smile_cat:

File: R/foreign.R [hunk 2]
```diff
@@ -622,10 +623,10 @@ graph_from_graphdb <- function(url = NULL,
     typegroup <- typegroups[which(types == type)]
 
     if (!prefix %in% prefixes) {
-      stop("Invalid prefix!")
+      cli::cli_abort("{prefix} is not a valid prefix. Must be one of {prefixes}.")
     }
     if (!type %in% types) {
-      stop("Invalid graph type!")
+      cli::cli_abort("{type} is not a valid graph type. Must be one of {types}.")
```
Comment (maelle) [inline R/foreign.R:629]: maybe split this and the message above into two lines?
```suggestion
      cli::cli_abort(c(
      "{type} is not a valid graph type.",
      i = "Must be one of {types}."
    ))
```

File: R/foreign.R [hunk 3]
```diff
@@ -596,12 +596,13 @@ write.graph.dot <- function(graph, file, ...) {
...
 #' @export
 #' @keywords graphs
-graph_from_graphdb <- function(url = NULL,
-                               prefix = "iso", type = "r001", nodes = NULL, pair = "A", which = 0,
-                               base = "http://cneurocvs.rmki.kfki.hu/graphdb/gzip",
-                               compressed = TRUE, directed = TRUE) {
+graph_from_graphdb <- function(
+    url = NULL,
+    prefix = "iso", type = "r001", nodes = NULL, pair = "A", which = 0,
+    base = "https://github.com/schochastics/graphsdb/raw/refs/heads/main",
```
Comment (maelle) [inline R/foreign.R:602]: could we instead use a permalink from the Zenodo record?

**Review by maelle — COMMENTED** [review]
good idea!

I see a typo in the file "algothitms", it could be fixed at the same time.

I wonder whether the database should be cached in an user dir. Should the argument of where to save it be exposed?

File: R/foreign.R (hunk 3 above)
Comment (schochastics) [reply R/foreign.R:602]: The zenodo link is unfortunately the whole db. You cannot just download a single file which is need for the function

Comment (maelle) [reply R/foreign.R:602]: Oh ok, sorry, makes sense, thank you.

Comment (maelle) [reply R/foreign.R:602]: Would we be allowed to store a copy in https://github.com/igraph/igraphdata?

**Comment by szhorvat** [comment]
> and hosted it here: https://github.com/schochastics/graphsdb/

I suggest hosting it under the igraph organization for the purposes of allowing the function to work.

In our own copy, we should mention the license and list the original authors, _in addition_ to linking to Zenodo. I'm really glads to see that this is on Zenodo given that the MIVIA website is gone now.

@maelle 

> Would we be allowed to store a copy in https://github.com/igraph/igraphdata?

This dataset is way too large for the igraphdata package. I suggest using a separate repo, exactly what @schochastics did, but under the igraph organization. I believe you _should_ be able to create a new repo, but if not let me know and I'll see if I can fix that.

----

Can this function operate with a local copy of the database? Would this be easy to implement, and if yes, can we include an explanation of how to do it? `file:///` URL in `base`?

----

Other than the comments above, this LGTM.

File: R/foreign.R (hunk 1 above)
Comment (schochastics) [reply R/foreign.R:599]: Yes :D. Should I revert it?

File: R/foreign.R (hunk 3 above)
Comment (schochastics) [reply R/foreign.R:602]: can confirm, the function works with a local copy of the database

**Comment by schochastics** [comment]
I will try to host it under the igraph org and put all the necessary information into the README. The files have a CC license so that should all be fine. I also checked that it works with a local copy. You simply need to provide the path to the database. I will also update the docs so that this is clear

File: R/foreign.R (hunk 1 above)
Comment (maelle) [reply R/foreign.R:599]: No! I was just curious.

File: R/foreign.R [hunk 4]
```diff
@@ -596,12 +596,13 @@ write.graph.dot <- function(graph, file, ...) {
...
 #' @keywords graphs
-graph_from_graphdb <- function(url = NULL,
-                               prefix = "iso", type = "r001", nodes = NULL, pair = "A", which = 0,
-                               base = "http://cneurocvs.rmki.kfki.hu/graphdb/gzip",
-                               compressed = TRUE, directed = TRUE) {
+graph_from_graphdb <- function(
+    url = NULL,
+    prefix = "iso", type = "r001", nodes = NULL, pair = "A", which = 0,
+    base = "https://github.com/igraph/graphsdb/raw/refs/heads/main",
+    compressed = TRUE, directed = TRUE) {
```
Comment (krlmlr) [inline R/foreign.R:603]:
```suggestion
graph_from_graphdb <- function(
  url = NULL,
  prefix = "iso",
  type = "r001",
  nodes = NULL,
  pair = "A",
  which = 0,
  base = "https://github.com/igraph/graphsdb/raw/refs/heads/main",
  compressed = TRUE,
  directed = TRUE
) {
```

File: R/foreign.R [hunk 5]
```diff
@@ -622,10 +629,13 @@ graph_from_graphdb <- function(url = NULL,
     typegroup <- typegroups[which(types == type)]
 
     if (!prefix %in% prefixes) {
-      stop("Invalid prefix!")
+      cli::cli_abort("{prefix} is not a valid prefix. Must be one of {prefixes}.")
```
Comment (krlmlr) [inline R/foreign.R:632]:
```suggestion
      cli::cli_abort(c(
        "{.value {prefix}} is not a valid prefix.",
        i = "Must be one of {.value {prefixes}}."
      ))
```

File: R/foreign.R [hunk 6]
```diff
@@ -622,10 +629,13 @@ graph_from_graphdb <- function(url = NULL,
...
     }
     if (!type %in% types) {
-      stop("Invalid graph type!")
+      cli::cli_abort(c(
+        "{type} is not a valid graph type.",
+        i = "Must be one of {types}."
+      ))
```
Comment (krlmlr) [inline R/foreign.R:638]:
```suggestion
      cli::cli_abort(c(
        "{.value {type}} is not a valid graph type.",
        i = "Must be one of {.value {types}}."
      ))
```

File: R/foreign.R [hunk 7]
```diff
@@ -641,7 +651,7 @@ graph_from_graphdb <- function(url = NULL,
 
   f <- try(gzcon(file(filename, open = "rb")))
   if (inherits(f, "try-error")) {
-    stop(paste("Cannot open URL:", filename))
+    cli::cli_abort("Cannot open URL:{.arg filename}")
```
Comment (krlmlr) [inline R/foreign.R:654]:
```suggestion
    cli::cli_abort("Cannot open URL provided in {.arg filename}: {.url {filename}}")
```

**Review by krlmlr — COMMENTED** [review]
Do these actually work and look better? Please merge when good and green.
