### PR TITLE
fix: `g + vertices(1, 2, foo = 3)` works again, regression introduced in igraph 2.0.0

### LINKED ISSUE #1231: `vertices(1, 2, foo = 3)` no longer works
### What happens?

Recycling of attributes is broken since igraph 2.0.0 .

Downstream: https://github.com/se-sic/coronet/pull/250

## CRAN

``` r
options(conflicts.policy = list(warn = FALSE))
library(igraph)

g <-
  make_empty_graph(1) +
  vertices("a", "b", foo = 5)
#> Error in add_vertices(e1, la, attr = e2): At rinterface_extra.c:78 : Expecting a scalar integer but received a vector of length 2. Invalid value

V(g)$foo
#> Error in eval(expr, envir, enclos): object 'g' not found
```

<sup>Created on 2024-02-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

## 1.6.0

``` r
options(conflicts.policy = list(warn = FALSE))
library(igraph)

g <-
  make_empty_graph(1) +
  vertices("a", "b", foo = 5)

V(g)$foo
#> [1] NA  5  5
```

<sup>Created on 2024-02-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by maelle**
Fix  #1231

Partly refactoring for understanding for now.

### CODE REVIEW

File: R/operators.R [hunk 1]
```diff
@@ -1079,22 +1079,23 @@ path <- function(...) {
   } else if ("igraph.vertex" %in% class(e2)) {
     ## Adding vertices, possibly with attributes
     ## If there is a single unnamed argument, that contains the vertex names
-    wn <- which(names(e2) == "")
-    if (length(wn) == 1) {
-      names(e2)[wn] <- "name"
+    unnamed_elements_indices <- which(!rlang::have_name(e2))
```
Comment (maelle) [inline R/operators.R:1082]: I guess wn stands for which not named or something like that.

Comment (maelle) [reply R/operators.R:1082]: and I find `!rlang::have_name()` more readable than `names(x) == ""`. https://masalmon.eu/2023/11/06/functions-dealing-with-names/

File: R/operators.R [hunk 2]
```diff
@@ -1079,22 +1079,23 @@ path <- function(...) {
...
+    if (length(unnamed_elements_indices) == 1) {
+      e2 <- rlang::set_names(e2[unnamed_elements_indices], "name")
```
Comment (maelle) [inline R/operators.R:1084]: I guess the readability of this line is not obviously better but since I was using rlang above...

File: R/operators.R [hunk 3]
```diff
@@ -1079,22 +1079,23 @@ path <- function(...) {
...
     } else if (is.null(names(e2))) {
       ## No names at all, everything is a vertex name
       e2 <- list(name = unlist(e2, recursive = FALSE))
-    } else if (length(wn) == 0) {
+    } else if (length(unnamed_elements_indices) == 0) {
       ## If there are no non-named arguments, we are fine
     } else {
       ## Otherwise, all unnamed arguments are collected and used as
```
Comment (maelle) [inline R/operators.R:1091]: this is the case that was broken as far as I understand. Not sure why it works to fix it here.

File: R/operators.R [hunk 4]
```diff
@@ -1079,22 +1079,23 @@ path <- function(...) {
...
       ## vertex names
-      nn <- unlist(e2[wn], recursive = FALSE)
-      e2 <- c(list(name = nn), e2[names(e2) != ""])
+      nn <- unlist(e2[unnamed_elements_indices], recursive = FALSE)
+      e2 <- c(list(name = nn), e2[rlang::have_name(e2)])
     }
-    la <- unique(sapply(e2, length))
-    res <- add_vertices(e1, la, attr = e2)
+    # When adding vertices via +, all unnamed arguments are interpreted as vertex names of the new vertices.
```
Comment (maelle) [inline R/operators.R:1096]: this comes from the docs

**Comment by maelle** [comment]
``` r
library("igraph")
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union

g <- make_empty_graph(1)
g
#> IGRAPH bd455eb D--- 1 0 -- 
#> + edges from bd455eb:
V(g)
#> + 1/1 vertex, from bd455eb:
#> [1] 1

g <- g +
  vertices("a", "b", foo = 5)
g
#> IGRAPH 34a9a54 DN-- 3 0 -- 
#> + attr: name (v/c), foo (v/n)
#> + edges from 34a9a54 (vertex names):
V(g)
#> + 3/3 vertices, named, from 34a9a54:
#> [1] <NA> a    b
V(g)$foo
#> [1] NA  5  5
```

<sup>Created on 2024-02-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

File: R/operators.R [hunk 5]
```diff
@@ -1079,22 +1079,23 @@ path <- function(...) {
...
       ## If there are no non-named arguments, we are fine
     } else {
       ## Otherwise, all unnamed arguments are collected and used as
       ## vertex names
-      nn <- unlist(e2[wn], recursive = FALSE)
-      e2 <- c(list(name = nn), e2[names(e2) != ""])
+      nn <- unlist(e2[unnamed_elements_indices], recursive = FALSE)
+      e2 <- c(list(name = nn), e2[rlang::have_name(e2)])
     }
-    la <- unique(sapply(e2, length))
```
Comment (maelle) [inline R/operators.R:1096]: why was this supposed to be nv? I think my change here is the fix.

**Review by krlmlr — COMMENTED** [review]
Thanks. Since we obviously didn't have any tests, can you please add some?

File: tests/testthat/test-operators.R [hunk 6]
```diff
@@ -91,3 +91,17 @@ test_that("t() is aliased to edge reversal for graphs", {
...
 })
+
+test_that("vertices() works", {
+  g <- make_empty_graph(1)
+
+  g_all_unnamed <-  g + vertices("a", "b")
+  expect_s3_class(V(g_all_unnamed), "igraph.vs")
+  expect_identical(V(g_all_unnamed)$name, c( NA, "a", "b"))
+
+  g_mix_named_unnamed <- g + vertices("a", "b", foo = 5)
```
Comment (krlmlr) [inline tests/testthat/test-operators.R:102]: What happens with `foo = 6:7` and `foo = 8:10` ?

**Comment by maelle** [comment]
I added a test but I'm surprised I need to use `unname()`, is something wrong:
``` r
library("igraph")
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union

g <- make_empty_graph(1)
g
#> IGRAPH ea2b4e5 D--- 1 0 -- 
#> + edges from ea2b4e5:
V(g)
#> + 1/1 vertex, from ea2b4e5:
#> [1] 1

g <- g +
  vertices("a", "b", foo = 5)
g
#> IGRAPH 6aaaab9 DN-- 3 0 -- 
#> + attr: name (v/c), foo (v/n)
#> + edges from 6aaaab9 (vertex names):
V(g)
#> + 3/3 vertices, named, from 6aaaab9:
#> [1] <NA> a    b
V(g)$name
#> <NA> <NA> <NA> 
#>   NA  "a"  "b"
V(g)$foo
#> [1] NA  5  5
```

<sup>Created on 2024-02-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

And with v1.6.0, it's the same actually

``` r
library("igraph")
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union

g <- make_empty_graph(1)
g
#> IGRAPH c331734 D--- 1 0 -- 
#> + edges from c331734:
V(g)
#> + 1/1 vertex, from c331734:
#> [1] 1

g <- g +
  vertices("a", "b", foo = 5)
g
#> IGRAPH dc14fb9 DN-- 3 0 -- 
#> + attr: name (v/c), foo (v/n)
#> + edges from dc14fb9 (vertex names):
V(g)
#> + 3/3 vertices, named, from dc14fb9:
#> [1] <NA> a    b
V(g)$name
#> <NA> <NA> <NA> 
#>   NA  "a"  "b"
V(g)$foo
#> [1] NA  5  5
```

<sup>Created on 2024-02-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

We can discuss later today. :smile_cat:

File: tests/testthat/test-operators.R (hunk 6 above)
Comment (maelle) [reply tests/testthat/test-operators.R:102]: I added a test. The error also happens with v1.6.0 and seems logical.

File: R/operators.R (hunk 1 above)
Comment (krlmlr) [reply R/operators.R:1082]: They are different, though, if the vector is unnamed.

```suggestion
    unnamed_elements_indices <- which(names(e2) == "")
```
